- name: add postgresql apt repogitory key
  tags: nginx
  apt_key: url=http://nginx.org/keys/nginx_signing.key
    state=present

- name: add nginx apt deb repogitory
  tags: nginx
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ precise nginx'
    state=present update_cache=yes

- name: add nginx apt deb-src repogitory
  tags: nginx
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu/ precise nginx'
    state=present update_cache=yes

- name: install nginx
  tags: nginx
  apt: pkg={{item}} force=yes update_cache=yes
  with_items:
    - nginx 

- name: create nginx config
  tags: nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes
  notify:
    - restart nginx
